name: build-dpdk-docset
on:
  workflow_dispatch:
    inputs:
      dpdk_rev:
        description: 'DPDK revision'
        default: 'releases'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools
        run:  sudo apt-get update && sudo apt-get install -y meson ninja-build build-essential python3-pyelftools doxygen sphinx-common
      - name: Checkout DPDK repo
        uses: actions/checkout@v3
        with:
          repository: DPDK/dpdk
          path: dpdk
          ref: ${{ inputs.dpdk_rev }}
      - name: Checkout dpdk-dash repo
        uses: actions/checkout@v3
        with: 
          path: dpdk-dash
      - name: Configure DPDK build
        run:  pwd && cd dpdk && meson /tmp/build -Denable_docs=true && cat $GITHUB_WORKSPACE/dpdk-dash/doxy-api.conf >> /tmp/build/doc/api/doxy-api.conf
      - name: Build DPDK docs
        run:  cd /tmp/build && ninja doc
      - name: Install doxygen2docset
        run:  sudo apt-get install -y ./dpdk-dash/doxygen2docset.deb
      - name: Build Dash docset
        run:  cat /tmp/build/doc/api/html/Info.plist && doxygen2docset --doxygen /tmp/build/doc/api/html --docset /tmp/build/docset
      - name: Set icon
        run:  cp dpdk-dash/icon/icon.png /tmp/build/docset/dpdk.docset/
      - name: Compress
        run:  cd /tmp/build/docset && tar -czf /tmp/dpdk.tar.gz dpdk.docset
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: DPDK-${{ inputs.dpdk_rev }}.docset
          path: /tmp/dpdk.tar.gz
